# Generated by Django 3.1.7 on 2023-07-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafileupload',
            name='cpf_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datafileupload',
            name='file_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datafileupload',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='datafileupload',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
    ]
